"""Constants for web scraper."""

from src.shared.types.location import Category

ATLAS_OBSCURA_CONFIG = {
    "base_url": "https://www.atlasobscura.com",
    "nyc_things_to_do": "https://www.atlasobscura.com/things-to-do/new-york-city",
    "nyc_places": "https://www.atlasobscura.com/places?lat=40.7128&lng=-74.0060",
    "rate_limit_seconds": 2.0,
    "max_pages": 5,
    "items_per_page": 20,
}

GOOGLE_MAPS_TYPE_MAPPING = {
    "bakery": Category.CAFE,
    "bar": Category.NIGHTLIFE,
    "cafe": Category.CAFE,
    "campground": Category.NATURE,
    "casino": Category.NIGHTLIFE,
    "cemetery": Category.HISTORICAL,
    "church": Category.HISTORICAL,
    "city_hall": Category.HISTORICAL,
    "clothing_store": Category.SHOPPING,
    "convenience_store": Category.SHOPPING,
    "department_store": Category.SHOPPING,
    "establishment": Category.LOCAL,
    "food": Category.RESTAURANT,
    "gym": Category.RELAXATION,
    "hair_care": Category.LOCAL,
    "health": Category.LOCAL,
    "hindu_temple": Category.HISTORICAL,
    "hospital": Category.LOCAL,
    "library": Category.LOCAL,
    "light_rail_station": Category.LOCAL,
    "liquor_store": Category.SHOPPING,
    "local_government_office": Category.LOCAL,
    "meal_delivery": Category.RESTAURANT,
    "meal_takeaway": Category.RESTAURANT,
    "mosque": Category.HISTORICAL,
    "movie_theater": Category.LOCAL,
    "museum": Category.MUSEUM,
    "night_club": Category.NIGHTLIFE,
    "park": Category.NATURE,
    "parking": Category.LOCAL,
    "pet_store": Category.SHOPPING,
    "place_of_worship": Category.HISTORICAL,
    "police": Category.LOCAL,
    "post_office": Category.LOCAL,
    "restaurant": Category.RESTAURANT,
    "school": Category.LOCAL,
    "shoe_store": Category.SHOPPING,
    "shopping_mall": Category.SHOPPING,
    "spa": Category.RELAXATION,
    "stadium": Category.LOCAL,
    "store": Category.SHOPPING,
    "subway_station": Category.LOCAL,
    "supermarket": Category.SHOPPING,
    "synagogue": Category.HISTORICAL,
    "tourist_attraction": Category.HISTORICAL,
    "train_station": Category.LOCAL,
    "transit_station": Category.LOCAL,
    "travel_agency": Category.LOCAL,
    "university": Category.LOCAL,
    "veterinary_care": Category.LOCAL,
    "zoo": Category.NATURE,
}

KEYWORD_CATEGORY_MAPPING = {
    "cafe": Category.CAFE,
    "coffee": Category.CAFE,
    "espresso": Category.CAFE,
    "bakery": Category.CAFE,
    "restaurant": Category.RESTAURANT,
    "diner": Category.RESTAURANT,
    "bar": Category.NIGHTLIFE,
    "pub": Category.NIGHTLIFE,
    "brewery": Category.NIGHTLIFE,
    "cocktail": Category.NIGHTLIFE,
    "museum": Category.MUSEUM,
    "gallery": Category.MUSEUM,
    "exhibit": Category.MUSEUM,
    "park": Category.NATURE,
    "garden": Category.NATURE,
    "trail": Category.NATURE,
    "historic": Category.HISTORICAL,
    "landmark": Category.HISTORICAL,
    "monument": Category.HISTORICAL,
    "shop": Category.SHOPPING,
    "store": Category.SHOPPING,
    "market": Category.SHOPPING,
    "spa": Category.RELAXATION,
    "wellness": Category.RELAXATION,
    "yoga": Category.RELAXATION,
    "adventure": Category.ADVENTURE,
    "escape": Category.ADVENTURE,
    "climb": Category.ADVENTURE,
    "festival": Category.FESTIVAL,
    "market": Category.FESTIVAL,
}

CATEGORY_PRIORITY = [
    Category.CAFE,
    Category.RESTAURANT,
    Category.NIGHTLIFE,
    Category.NATURE,
    Category.MUSEUM,
    Category.HISTORICAL,
    Category.SHOPPING,
    Category.RELAXATION,
    Category.ADVENTURE,
    Category.FESTIVAL,
    Category.LOCAL,
]
